heroku/userdatabasedotcom/config/routes.rb
Userdatabasedotcom::Application.routes.draw do
  
  
  match "user/result"
  match "user/update"
  match "user/index"
  get "user/search"
  get "user/index"
  get "user/update"
  get "user/new"
  match "user/:id", :to => "user#edit"
  match "user/:id/save" , :to => "user#save"
  get "sessions/create"
  
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#fail'
  root :to => 'user#index'

end

heroku/userdatabasedotcom/app/models/session.rb
class Session < ActiveRecord::Base
  def self.sweep(time = 1.hour)
    time = time.split.inject { |count, unit|
        count.to_i.send(unit)
      } if time.is_a?(String)
      
    delete_all "created_at < '#{time.ago.to_s(:db)}'"
  end
end

heroku/userdatabasedotcom/app/controllers/sessions_controller.rb
  class SessionsController < ApplicationController
    def create
      reset_session 
      ENV['sfdc_token'] = request.env['omniauth.auth']['credentials']['token']
      ENV['sfdc_instance_url'] = request.env['omniauth.auth']['instance_url']
   #   authentication = Authentication.find_or_create_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      p " logged"
      p request.env['omniauth.auth'].inspect
     session[:token] = request.env['omniauth.auth']["credentials"]["token"]
     session[:uri] = request.env['omniauth.auth']["instance_url"]
      #render :text => Accounts.get_first_hundred.inspect
      #render :text => Contacts.get_contacts.inspect
      flash[:notice] = "Authentication successful."
      redirect_to :controller => 'user', :action => 'index'
   end
    def fail
      render :text =>  request.env["omniauth.auth"].to_yaml
    end
    def destroy  
    reset_session  
    flash[:notice] = "Logged out." 
  #  redirect_to posts_url 
  end
  end

heroku/userdatabasedotcom/app/controllers/user_controller.rb
 require 'rubygems'
  require 'httparty'
  require 'nokogiri'
  require 'open-uri'
  require 'databasedotcom'
  require 'uri'
  require 'pg'
  require 'openssl'
class UserController < ApplicationController
  include HTTParty
  include Nokogiri
  include Databasedotcom
 
  def set_headers
 #   headers 'Authorization' => "OAuth #{ENV['sfdc_token']}"
      ENV['sfdc_token'] = request.env['omniauth.auth']['credentials']['token']
      ENV['sfdc_instance_url'] = request.env['omniauth.auth']['instance_url']
    session[:token] = ENV['sfdc_token']
    session[:uri] =  ENV['sfdc_instance_url']  
  end

  
  def authorize
 #   set_headers
    p " output"
#p     ENV['sfdc_token'] = request.env['omniauth.auth']['credentials']['token']
#p      ENV['sfdc_instance_url'] = request.env['omniauth.auth']['instance_url']
    p session[:token] = "00DU0000000ITUe!ASAAQEUhXsO_Yo.vM.3ESPAKBvyUTDeZfkEK0Ji0Nh2HPCeGhVT8wHMbGw2rlxQEZ.qh1XQf_Gz5ik9kaDbE3Oq0cdnwQvCh"
    p session[:uri] ="https://na12.salesforce.com"
#    p request.env['omniauth.auth'].inspect
p    client = Databasedotcom:: Client.new 
    client.authenticate(:options => nil, :token => session[:token], :instance_url => session[:uri])
#   p client.authenticate request.env['omniauth.auth']  
    users = client.materialize("User")
    roles = client.materialize("UserRole")
    profiles = client.materialize("Profile")
    session[:client] = client
  end
  def index
    # this can be dropped after all the debugging is done as 
    #this is an unwanted query from sfdc
    
    search
    userId= Array.new
    @users = User.all
    @users.each do |user| 
        user = user.Id[0..-4]
        userId.push(user)
      end
     
     @users
  
#  @result = Pardb.find_by_sfdc_id(userId, :select => "par_un, par_pw")
  end
  
  def search
    authorize
    @rolenames = Hash.new
    @profilenames = Hash.new
    @rolenames[0] = 'All'
    @profilenames[0] = 'All'
    @roles = UserRole.query("Portaltype='None'")
    @roles.each { |role|  @rolenames[role.Id] = role.Name }
    @profiles = Profile.all
    @profiles.each { |profile| @profilenames[profile.Id] = profile.Name}   
    session[:roles] = @rolenames
    session[:profiles] = @profilenames
    @rolenames = Hash[session[:roles].sort_by {|k,v| v}]
    @profilenames = Hash[session[:profiles].sort_by {|k,v| v}]
  end
  
  def get_search_criteria
    # replace role and profile with their corresponding ids
    criteria = Hash.new
    params[:name].blank? ?  criteria.except['name'] : criteria['name'] = params[:name].split()[0].capitalize 
    if params['role'] != 'All' then  criteria['role'] = session[:roles].key(params[:role]) end
    if params['profile'] != 'All'  then criteria['profile'] = session[:profiles].key(params[:profile])  end
    params[:active] == "1" ?  criteria['active'] = true :  criteria['active'] = false
    criteria
  end
  
  def result
    criteria = get_search_criteria
    criteriastring = ''
    userId= Array.new
    criteriastring = "FirstName = '#{criteria['name']}' and " if criteria['name']
    criteriastring = criteriastring + "UserRoleId = '#{criteria['role']}' and " if criteria['role']
    criteriastring = criteriastring + "ProfileId = '#{criteria['profile']}' and " if criteria['profile']
    criteriastring = criteriastring + "IsActive = #{criteria['active']} and " 
     if criteriastring.length > 0  
       criteriastring = criteriastring[0..-5]
     end
     
      @users= User.query(criteriastring)
      @users.each do |user| 
        user = user.Id[0..-4]
        userId.push(user)
      end
       session[:users] = @users
    #  @result = Pardb.find_all_by_sfdc_id(userId, :select => "id, par_un, par_pw")
    #  @result.each{ |res| session[:id] = res.id}
  end
   def edit
     p params[:id]
     
     @users = Array.new
     @user = Array.new
     @users = session[:users]
     @users.each do |user|
       if user.Id == params[:id]
        @user.push(user)
         
       end
     end
     
     @rolenames = Hash[session[:roles].sort_by {|k,v| v}]
     @profilenames = Hash[session[:profiles].sort_by {|k,v| v}]
     p @user
  end
  def save
    session[:roles] = params[:roles]
    session[:profiles] = params[:profiles] 
    update_hash = Hash.new
      p "update"
   # update_hash["Name"] = params[:name]
    update_hash["Email"] = params[:email]
    update_hash["IsActive"] = params[:active] == "true" ? true : false
     update_hash["UserRoleId"] = session[:roles].key(params[:role]) if params[:role] != "All"
    update_hash["ProfileId"] = session[:profiles].key(params[:profile]) if params[:profile] != "All"
    User.upsert("Id", params[:id], update_hash)
    redirect_to :controller => 'user', :action => "index"
  end

end

heroku/userdatabasedotcom/app/helpers/application_helper.rb
module ApplicationHelper
  def flatten_hash(hash = params, ancestor_names = [])
    flat_hash = {}
    hash.each do |k, v|
      names = Array.new(ancestor_names)
      names << k
      if v.is_a?(Hash)
        flat_hash.merge!(flatten_hash(v, names))
      else
        key = flat_hash_key(names)
        key += "[]" if v.is_a?(Array)
        flat_hash[key] = v
      end
    end

    flat_hash
  end

  def flat_hash_key(names)
    names = Array.new(names)
    name = names.shift.to_s.dup 
    names.each do |n|
      name << "[#{n}]"
    end
    name
  end

  def hash_as_hidden_fields(hash = params)
    hidden_fields = []
    flatten_hash(hash).each do |name, value|
      value = [value] if !value.is_a?(Array)
      value.each do |v|
        hidden_fields << hidden_field_tag(name, v.to_s, :id => nil)          
      end
    end

    hidden_fields.join("\n")
  end
end

heroku/userdatabasedotcom/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Userdatabasedotcom</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

heroku/userdatabasedotcom/app/views/user/_user.html.erb
<span id="title" >User Detail</span>
<% form_tag  :controller => 'user', :action => 'update' do  %>

<table border="0" cellspacing="1" cellpadding="5" bgcolor="#CCCCCC" >
	<tr id="label2" >
		
		<th> Name </th>
		<th> Email </th>
		<th> Active Status </th>
		<th> SFDC Username</th>
		<th> Title </th>
		<th> UserName </th>
		<th> UserType </th>
		<th> Country </th>
		<th> Role </th>
		<th> Profile </th>
				
	</tr>
	
 <% if @users.blank? %>
   	<th>No users found </th>
  <% else %>
  <% @users.each do |user| %>
	<tr id = "text2">
		<% if var == 'index' %>
			<td><%= user.Name %></td>
		<% else %>
				<td><a href="/user/<%= user.Id%>"><%= user.Name %></a></td>
		<% end %>
		<td><%= user.Email %></td>
		<% checked = false %>      
  		<td><%= check_box_tag 'IsActive', user.IsActive , user.IsActive == true ? checked=true : checked= false,  :disabled => true %></td>
		<td></td>
		<td><%= user.Title %></td>
		<td><%= user.Username %></td>
		<td><%= user.UserType %></td>
		<td><%= user.PAR121__PAR_Country__c %></td>
		<% if user.UserRoleId %>
			<td><%= user.UserRoleId %> <%= " / " %>
				<%= session[:roles][user.UserRoleId] %></td>
		<% else %>
			<td></td>
		<% end %>
		<% if user.ProfileId %>
			<td><%= user.ProfileId %><%= " / " %><%= session[:profiles][user.ProfileId] %></td>
		<% else %>
			<td></td>
		<% end %>
		
		
	</tr>
  <% end %>
  <% end %>
  </table>


<p><%= link_to 'Search for User', user_search_path() %>
	</p>

 <% end %>

heroku/userdatabasedotcom/app/views/user/edit.html.erb
<span id="title" >Edit User</span>
<p/>

<form method="post" action="/user/<%=  params[:id] %>/save"> 
<table border="0" cellspacing="1" cellpadding="5" bgcolor="#CCCCCC">
	<% @user.each do |user| %>
	
	<tr>
		<td id="label">Name</td>
		<td id= "text"><%= user.Name %>  </td>
	</tr>
	
	<tr>
		<td id="label">Email</td>
		<td id= "text"><input type="email" name="email" value="<%= user.Email %>" size=50 </td>
	</tr>
	<tr>
		<td id="label" >Active Status</td>
		
		<% checked = false %>
		<td id= "check"><%= check_box_tag 'active', "#{user.IsActive}", user.IsActive == true ? checked=true : checked= false,  :disabled => false %>  </td>
	</tr>
	<tr >
		<td id="label" >SFDC Name</td>
		<td id= "text"><%= user.Username %></td>
	</tr>
	<tr >
		<td  id="label" >Role</td>
		<td id= "list"><%= select_tag "role", options_for_select(@rolenames.values, "#{session[:roles][user.UserRoleId]}")  %></td>
	</tr>
	<tr >
		
		<td  id="label" >Profile</td>
		<td id= "list"><%= select_tag "profile", options_for_select(@profilenames.values, "#{session[:profiles][user.ProfileId]}") %></td>
	</tr>	
	<% end %>
	
 		<%= raw hash_as_hidden_fields(:roles => session[:roles]) %>	
 		<%= raw hash_as_hidden_fields(:profiles => session[:profiles]) %>
 		
	<tr> 
		<td id = 'label'></td>
		<td id = 'button' colspan="2"  align="center"><input type="submit" value="Submit" ></td> 
	</tr>	
</table>	
<span id="link"><a href="/user/index">Cancel</a></span><p/>

heroku/userdatabasedotcom/app/views/user/index.html.erb
<%= render 'user', :var => 'index' %>

heroku/userdatabasedotcom/app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

heroku/userdatabasedotcom/app/views/user/result.html.erb
<p> Click on a name to edit the record </p>
<%= render 'user', :var => 'result' %>

heroku/userdatabasedotcom/app/views/user/search.html.erb
<span id="title" >Enter Search Criteria</span>
<% form_tag  :controller => 'user', :action => 'result' do  %>
<table border="0" cellspacing="1" cellpadding="5" bgcolor="#CCCCCC" >
  <tr>
    <td id="label"> Role </td>
   <td id= "list"><%= select_tag "role", options_for_select(@rolenames.values) %></td>
 </tr>
 <tr>
    <td id="label" ><label> Profile </label></td>
    <td id= "list"><%= select_tag "profile", options_for_select(@profilenames.values) %></td>
 </tr>
 <tr>
	<td id="label">First Name</td>
     <td id= "text"><%= text_field_tag "name", '', :size => 40  %> </td>
 </tr>
 <tr>
      <td id="label" ><label>  Active </label></td>
     <td id= "check"> <%= check_box_tag 'active', '1', true %></td>
 </tr>
 
    <td id = 'label'></td>
	<td id = 'button' colspan="2"  align="center"><%= submit_tag "Get User Details"  %></td>
 
 </table>
<% end %>

<span id="link"><a href="/user/index">Cancel</a></span><p/>